import { Place } from "@/lib/types";

export const MOCK_PLACES: Place[] = [
  { id: "nyc-1", name: "Los Tacos No.1", city: "NYC", category: "food", vibeTags: ["local", "high-energy"], priceLevel: "budget", estimatedVisitDurationMins: 60, neighborhood: "Chelsea", latitude: 40.742, longitude: -74.006, openingHours: "Daily 11:00-22:00", sourceCredibilityScore: 0.84, specificityScore: 0.75, popularityScore: 0.92, description: "Beloved taco spot with quick service and authentic flavors." },
  { id: "nyc-2", name: "West Village Coffee Walk", city: "NYC", category: "cafes", vibeTags: ["cozy", "walkable", "aesthetic"], priceLevel: "moderate", estimatedVisitDurationMins: 90, neighborhood: "West Village", latitude: 40.734, longitude: -74.002, openingHours: "Daily 08:00-18:00", sourceCredibilityScore: 0.78, specificityScore: 0.68, popularityScore: 0.8, description: "A stitched route of cafe stops in leafy streets." },
  { id: "nyc-3", name: "The Jazz Gallery", city: "NYC", category: "nightlife", vibeTags: ["local", "low-tourist", "cozy"], priceLevel: "premium", estimatedVisitDurationMins: 120, neighborhood: "Flatiron", latitude: 40.744, longitude: -73.989, openingHours: "Shows most nights", sourceCredibilityScore: 0.82, specificityScore: 0.72, popularityScore: 0.76, description: "Intimate modern jazz venue for serious listeners." },
  { id: "lisbon-1", name: "Time Out Market", city: "Lisbon", category: "food", vibeTags: ["aesthetic", "high-energy"], priceLevel: "moderate", estimatedVisitDurationMins: 90, neighborhood: "Cais do Sodre", latitude: 38.706, longitude: -9.145, openingHours: "Daily 10:00-00:00", sourceCredibilityScore: 0.86, specificityScore: 0.7, popularityScore: 0.9, description: "Curated market with standout chefs and local classics." },
  { id: "lisbon-2", name: "Alfama Hidden Fado Courtyard", city: "Lisbon", category: "hidden gems", vibeTags: ["historic", "local", "low-tourist"], priceLevel: "moderate", estimatedVisitDurationMins: 75, neighborhood: "Alfama", latitude: 38.712, longitude: -9.13, openingHours: "Evenings", sourceCredibilityScore: 0.79, specificityScore: 0.84, popularityScore: 0.67, description: "A quieter fado courtyard with traditional performances." },
  { id: "lisbon-3", name: "LX Factory Design Loop", city: "Lisbon", category: "shopping", vibeTags: ["trendy", "aesthetic", "walkable"], priceLevel: "premium", estimatedVisitDurationMins: 120, neighborhood: "Alcantara", latitude: 38.703, longitude: -9.178, openingHours: "Daily 11:00-20:00", sourceCredibilityScore: 0.8, specificityScore: 0.69, popularityScore: 0.85, description: "Concept stores, books, and creative studios in old warehouses." },
  { id: "tokyo-1", name: "Tsukiji Outer Market Morning", city: "Tokyo", category: "food", vibeTags: ["local", "high-energy", "walkable"], priceLevel: "moderate", estimatedVisitDurationMins: 90, neighborhood: "Tsukiji", latitude: 35.665, longitude: 139.77, openingHours: "Morning focused", sourceCredibilityScore: 0.91, specificityScore: 0.8, popularityScore: 0.93, description: "Legendary seafood stalls and small specialty counters." },
  { id: "tokyo-2", name: "Yanaka Old Streets", city: "Tokyo", category: "local culture", vibeTags: ["historic", "cozy", "low-tourist"], priceLevel: "budget", estimatedVisitDurationMins: 120, neighborhood: "Yanaka", latitude: 35.727, longitude: 139.766, openingHours: "Always open", sourceCredibilityScore: 0.83, specificityScore: 0.81, popularityScore: 0.7, description: "Traditional neighborhood walk with temples and snack shops." },
  { id: "tokyo-3", name: "Shibuya Sky Sunset", city: "Tokyo", category: "nightlife", vibeTags: ["aesthetic", "trendy", "high-energy"], priceLevel: "premium", estimatedVisitDurationMins: 60, neighborhood: "Shibuya", latitude: 35.659, longitude: 139.7, openingHours: "10:00-22:30", sourceCredibilityScore: 0.89, specificityScore: 0.7, popularityScore: 0.95, description: "Iconic skyline deck ideal before evening plans." },
  { id: "dubai-1", name: "Alserkal Avenue Art Walk", city: "Dubai", category: "museums", vibeTags: ["aesthetic", "local", "trendy"], priceLevel: "moderate", estimatedVisitDurationMins: 120, neighborhood: "Al Quoz", latitude: 25.133, longitude: 55.231, openingHours: "Most galleries 10:00-19:00", sourceCredibilityScore: 0.84, specificityScore: 0.8, popularityScore: 0.77, description: "Cluster of galleries and creative spaces for contemporary art and design." },
  { id: "dubai-2", name: "Jumeirah Sunrise Beach Cafe Loop", city: "Dubai", category: "cafes", vibeTags: ["cozy", "aesthetic", "walkable"], priceLevel: "moderate", estimatedVisitDurationMins: 90, neighborhood: "Jumeirah", latitude: 25.197, longitude: 55.234, openingHours: "Daily 07:00-18:00", sourceCredibilityScore: 0.8, specificityScore: 0.72, popularityScore: 0.82, description: "Beachside cafe route for a slower morning with ocean views." },
  { id: "dubai-3", name: "Old Dubai Souk and Creek Route", city: "Dubai", category: "local culture", vibeTags: ["historic", "local", "hidden gems"], priceLevel: "budget", estimatedVisitDurationMins: 150, neighborhood: "Deira", latitude: 25.269, longitude: 55.296, openingHours: "Daily 10:00-22:00", sourceCredibilityScore: 0.87, specificityScore: 0.83, popularityScore: 0.79, description: "Traditional souks, abra crossing, and street food pockets around the creek." }
];
